### ISSUE TITLE
[BUG]: AIC calcuation

### ISSUE THREAD

**Issue by okenk** [kellijohnson-NOAA/indexwc#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current AIC values reported in aic_nll.txt are negative. AIC be positive though since NLL is positive. Formula is 2 n_pars - 2 loglikelihood

Note -2 loglikelihood. If using NLL (from optimization) formula is 2 n_pars PLUS 2 NLL

### Expected Behavior

AIC should generally be positive.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by kellijohnson-NOAA** [comment]
I am just using what {sdmTMB} reports. Here is the code
```
extractAIC.sdmTMB <- function(fit, scale, k = 2, ...) {
  L <- logLik(fit)
  edf <- attr(L, "df")
  return(c(edf, c(-2 * L + k * edf)))
}
```
which can be found [here](https://github.com/pbs-assess/sdmTMB/blob/cb492a6fe3fbb6b4ac20e975f6e17bd6d8241370/R/methods.R#L73)

**Comment by kellijohnson-NOAA** [comment]
Ahh, I see the problem. It is my fault 😮‍💨 . I am labeling the log likelihood as the "NLL" or negative log likelihood, which is incorrect. @okenk would you prefer that I fix the label or fix the value?

**Comment by kellijohnson-NOAA** [comment]
I changed the value to match the NLL label. Please feel free to reopen the issue if you would like the log likelihood to be saved instead.
