### ISSUE TITLE
[BUG]: Presence of large files in commit history

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [kellijohnson-NOAA/indexwc#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are potentially large files in the commit history that can be removed.

**Comment by seananderson** [comment]
Can easily fix with BFG
https://rtyley.github.io/bfg-repo-cleaner/
but it (or any history rewriting) requires anyone with push access to
reclone or they’ll just push the files back.

**Comment by kellijohnson-NOAA** [comment]
I talked to @chantelwetzel-noaa and she was fine with recloning. I am assuming you and @ericward-noaa will be okay with either forcing a reset or recloning? Please let me know if you aren't and we can find some other path forward.

**Comment by ericward-noaa** [comment]
Yep totally agree - there shouldn't be any large files here. So am fine with recloning

**Comment by seananderson** [comment]
The only really big file was that `sandbox/dover_example/sdmTMB_save.RData` file. I removed it from history with BFG and updated the gitignore (you'll need to force add .RData files now). Everyone needs to grab a fresh clone.

**Comment by ericward-noaa** [comment]
No need to archive this -- I think you should modify as you see fit. 

This is tangential, but if helpful, I've put together this repo demonstrating automation of index standardization with sdmTMB: https://github.com/ecosystem-state/wcbts-auto

**Comment by kellijohnson-NOAA** [comment]
Removed all [rR][dD]ata and png files with [3cda550](https://github.com/kellijohnson-NOAA/indexwc/commit/3cda55028182a1ee8f4b7fd6dbc3d8bd6217b28f). The repository is now super quick to clone after doing some garbage collection thanks to @seananderson's tips and bfg.

**Comment by kellijohnson-NOAA** [comment]
Big files are still in the repository see Pull request #10 and comment from @seananderson . I will fix this once and for all after merging in the pull request and prior to bringing the repository to pfmc-assessments.

**Comment by kellijohnson-NOAA** [comment]
I removed the files, so new clones will be needed, but because we have closed pull requests I am not actually sure if the history is entirely deleted. I was alerted with
```
 + 2f4851b...1032827 main -> main (forced update)
 ! [remote rejected] refs/pull/10/head -> refs/pull/10/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/12/head -> refs/pull/12/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/14/head -> refs/pull/14/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/16/head -> refs/pull/16/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/2/head -> refs/pull/2/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/3/head -> refs/pull/3/head (deny updating a hidden ref)
error: failed to push some refs to 'https://github.com/kellijohnson-NOAA/indexwc.git'
```
which google told me was because I have Pull Requests in the repository. I am not super concerned about it right now, the repo already downloads 10x faster.
