### ISSUE TITLE
[BUG]: too many GitHub package dependencies leads to API rate limit exceeded

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [kellijohnson-NOAA/indexwc#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installing {indexwc} on a fairly new machine leads to too many packages being installed and 
```
API rate limit exceeded
```

### Expected Behavior

The package would have loaded seamlessly after using `load_all()` or `remotes::install_github()`.

### Environment

```markdown
- OS: Windows
- Node:
- npm:
```

### Anything else?

I think eliminating the need for {VASTWestCoast} would help this a lot. @chantelwetzel-noaa if we need to do comparisons would it be alright to set those up in {VASTWestCoast} rather than here?

**Comment by seananderson** [comment]
Obviously good to limit the number of packages that need to be installed, but you can likely fix this by setting a GitHub PAT. https://github.com/r-lib/remotes/issues/210#issuecomment-430643547  which is a good idea anyways.
